software-tools-in-javascript/js4ds

promises.tex
This resolves https://github.com/software-tools-in-javascript/js4ds/issues/2
=> adding colon to promises post (issue #2)

promises.tex, src/promises/echo.js
=> Explaining the use of process.argv.

vis.tex
Proposed fix for https://github.com/software-tools-in-javascript/js4ds/issues/8
=> updating vega src tags

basics.tex
Closes #43. Please merge is you think it's OK.
=> Defining constant

basics.tex
I still haven't found a way to easily visualize LaTeX so please advise if I've messed up my addition of what should be another JS code chunk [closes #44]
=> adding to the example of what it would look like without interpolation

basics.tex, src/basics/destructuring-fail.js
=> Explaining destructuring assignment.

intro.tex
=> adding to personal bio

book.tex, callbacks.tex, regexp.tex, src/regexp/match.js, testing.tex
=> Adding brief explanation of regular expressions.

callbacks.tex
This fixes #40 by adding clarification as comments within the code chunk. I don't think the book makes use of chunk comments so if you'd like me to address this in another way please advise.
=> adding comments to function var chunk

callbacks.tex
=> Better explanation of anonymous functions.

callbacks.tex, src/callbacks/shortened-pipeline.js
=> Explaining pipeline example in more detail

callbacks.tex
=> add example code to functional programming chunks so user can run

glossary.tex, pages.tex
=> Explaining top-level child node removal.

capstone.tex, db.tex, docs/index.html, dynamic.tex, htmlcss.tex, interactive.tex, logging.tex, pages.tex, promises.tex, server.tex
If it builds for you, I'll merge.
=> Minor tidy-ups to LaTeX.

pages.tex, src/pages/count-paragraphs.html
=> Fixing source files for id/class issue

glossary.tex, oop.tex
Needs more work - please add suggestions.
Closes #33.
=> Fuller explanation of constructors and `this`.

pages.tex
=> Fixing wording of exercise.

pages.tex
=> Explaining why we're going to need the nodes later.

pages.tex
=> changing the div id to fill rather than its class

oop.tex
This closes #32, but I defer to your experience if you think the flow is better the other way.
=> rather than have the class and extended in the same code chunk, split up

oop.tex, pages.tex
In an attempt to close #23 I wanted to give the reader some indication that we're not leaving them alone to dissect this code (because we go over it on the next page) and that it's a draft that we'll be refining anyways.
=> 23 explicitly stating code is rough draft

pages.tex
=> Explaining how to open tools

dynamic.tex
I'm only taking a stab here and *think* this is correct? If so, closes #14
=> 14-return-single-node

package.json, promises.tex
Closes #6 : The query was still returning as successful with the year 2108 so I changed the typo to the month `80`
=> make API error

callbacks.tex, docs/index.html, src/callbacks/reduce-1.js, src/callbacks/reduce-2.js, src/callbacks/reduce-3.js
-   Split the example in two.
-   Add a preliminary example.
-   Lengthier explanation.
Closes #35.
=> Lengthier explanation of Array.reduce.

dynamic.tex
Closes #110 -- I made this an aside and put it where I think it makes sense but happy to re-arrange if you think there's a better home for it.
=> adding text on escaping parcel

basics.tex, book.bib, callbacks.tex, capstone.tex, collab.tex, dataman.tex, db.tex, dedication.tex, docs/index.html, dynamic.tex, htmlcss.tex, interactive.tex, intro.tex, legacy.tex, oop.tex, pages.tex, promises.tex, server.tex, testing.tex, vis.tex
Lots of little changes - if you trust me, please go ahead and merge.
=> Regularizing paragraph indentation

intro.tex, keypoints/intro.tex
improve definition of npm. Closes [#140 ]
=> fix(140): mention npm as a build tool

dedication.tex
=> dedication

capstone.tex, src/capstone/back/data-manager.js
`DataManager` seemed to be the most obvious place to use Data-Forge in our capstone project. This PR shows the progress I've made so far in doing so.
The main issue that I keep bumping up against is how to gracefully handle missing data. Please read the modified text in `capstone.tex` for details, to save me replicating it here. Any advice on how I can improve the code and make it more concise? Also: any idea how to catch empty series in DF in general? 
@gvwilson @MayaGans
=> WIP: Data-Forge in capstone

dataman.tex
It could be that I'm just biased having played with this today, but I wanted to expand upon how the second argument for parse is a callback and really drive home that it can do whatever you need it to.
=> papa-parse

intro.tex
=> adding text where scripts live

dataman.tex
=> adding const colors

basics.tex
=> Fixing casing of index entry

docs/index.html, server.tex
@gvwilson @MayaGans @tobyhodges  could you please review the changes
=> fix: link to express js

capstone.tex
=> shorten lines in two code blocks

glossary.tex, interactive.tex, server.tex
=> Explaining API inline.

testing.tex
=> Explaining fixture inline.

basics.tex, dataforge.tex, dynamic.tex, htmlcss.tex, oop.tex, pages.tex
- Figure 2.3
- Figure 4.1
- Figure 5.1
- Figure 5.2
- Figure 5.3
- Figure 6.1
- Figure 6.2 [edited text, removed parenthetical statement about whitespace]
- Figure 7.1
- Figure 14.3
- Figure 14.4
=> Figure callout

htmlcss.tex
=> Reflowing callout box for internal links.

.wordlist
False errors in spelling check
=> Removing two misspelled words

glossary.tex
Addresses comment in https://github.com/software-tools-in-javascript/js4ds/pull/194#issuecomment-552227185
=> Reflowing fat arrow glossary entry

htmlcss.tex
=> Shorten URL for image example.

html-settings.tex, htmlcss.tex, legacy.tex, pdf-settings.tex, regexp.tex, server.tex
trying to fix the table numbering problem - this doesn't work but it's a step in the right direction
=> Ensuring right order of caption and label

dynamic.tex
=> correct package name to react-dom
